"""
╔═══════════════════════════════════════════════════════╗
║   SanStudio Build Engine                              ║
║   Developed by Santhosh A                             ║
║   https://a-santhosh-hub.github.io/in/               ║
╚═══════════════════════════════════════════════════════╝

Core packaging engine:
  1. Validates HTML project structure
  2. Scans and catalogs all assets
  3. Generates the runtime_main.py from template
  4. Runs PyInstaller to produce the .exe
  5. Handles icon conversion (PNG/JPG → .ico)
  6. Writes detailed build log
"""

import os
import sys
import json
import shutil
import subprocess
import tempfile
import time
import logging
from pathlib import Path
from datetime import datetime
from typing import Callable, Optional

# Optional Pillow for icon conversion
try:
    from PIL import Image as PILImage
    PILLOW_OK = True
except ImportError:
    PILLOW_OK = False

AUTHOR_URL = "https://a-santhosh-hub.github.io/in/"

# ── Runtime template (embedded as a Python string) ───────────────────────────
RUNTIME_TEMPLATE = r'''"""
SanStudio Runtime — auto-generated by SanConverter
App: {{APP_NAME}} v{{APP_VERSION}}
Developed by Santhosh A · https://a-santhosh-hub.github.io/in/
"""
import sys
import os
import json
import socket
import threading
import http.server
import socketserver
import webbrowser
import time

# ── Resource path (handles PyInstaller _MEIPASS) ─────────────────────────────
def _res(rel: str) -> str:
    base = getattr(sys, "_MEIPASS", os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base, rel)

PROJECT_DIR = _res("web_project")

# ── Config ───────────────────────────────────────────────────────────────────
APP_NAME        = "{{APP_NAME}}"
APP_VERSION     = "{{APP_VERSION}}"
APP_WIDTH       = {{APP_WIDTH}}
APP_HEIGHT      = {{APP_HEIGHT}}
FULLSCREEN      = {{FULLSCREEN}}
RESIZABLE       = {{RESIZABLE}}
DEVTOOLS        = {{DEVTOOLS}}
SPLASH_ENABLED  = {{SPLASH_ENABLED}}
SPLASH_DURATION = {{SPLASH_DURATION}}
AUTHOR          = "Developed by Santhosh A"
AUTHOR_URL      = "https://a-santhosh-hub.github.io/in/"

# ── Find a free TCP port ──────────────────────────────────────────────────────
def _free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]

PORT = _free_port()

# ── Silent HTTP server ────────────────────────────────────────────────────────
class _Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=PROJECT_DIR, **kwargs)

    def log_message(self, fmt, *args):
        pass  # Silence all output

    def end_headers(self):
        # CORS + cache headers so page works like a real local server
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Cache-Control", "no-cache, no-store, must-revalidate")
        super().end_headers()

def _run_server():
    with socketserver.TCPServer(("127.0.0.1", PORT), _Handler) as httpd:
        httpd.serve_forever()

# ── JS ↔ Python bridge ────────────────────────────────────────────────────────
class _Api:
    def open_url(self, url: str):
        """Open an external URL in the system browser."""
        webbrowser.open(url)

    def open_author(self):
        """Open author portfolio page."""
        webbrowser.open(AUTHOR_URL)

    def get_app_info(self) -> str:
        return json.dumps({
            "name":    APP_NAME,
            "version": APP_VERSION,
            "author":  AUTHOR,
        })

    def save_file(self, filename: str, data: str) -> str:
        """Save a text/data-URI file to the user's Downloads folder."""
        try:
            import base64, re
            downloads = os.path.join(os.path.expanduser("~"), "Downloads")
            os.makedirs(downloads, exist_ok=True)
            dest = os.path.join(downloads, filename)
            # Handle data URI
            match = re.match(r"data:[^;]+;base64,(.+)", data)
            if match:
                with open(dest, "wb") as f:
                    f.write(base64.b64decode(match.group(1)))
            else:
                with open(dest, "w", encoding="utf-8") as f:
                    f.write(data)
            return json.dumps({"ok": True, "path": dest})
        except Exception as e:
            return json.dumps({"ok": False, "error": str(e)})

# ── Footer injection snippet ──────────────────────────────────────────────────
FOOTER_JS = r"""
(function() {
  if (document.getElementById('__san_footer')) return;
  var el = document.createElement('div');
  el.id = '__san_footer';
  el.style.cssText = [
    'position:fixed','bottom:0','left:0','right:0',
    'height:28px','background:rgba(11,14,23,0.88)',
    'backdrop-filter:blur(8px)',
    'display:flex','align-items:center','justify-content:center',
    'font-family:Segoe UI,sans-serif','font-size:11px',
    'color:#6B7A99','z-index:2147483647','letter-spacing:.3px',
    'border-top:1px solid rgba(79,142,247,0.18)'
  ].join(';');
  el.innerHTML = '<span style="margin-right:4px">⬡</span>Developed by <a href="javascript:void(0)" onclick="pywebview.api.open_author()" style="color:#4F8EF7;text-decoration:none;margin-left:4px">Santhosh A</a>';
  document.body.appendChild(el);
})();
"""

# ── Splash window ─────────────────────────────────────────────────────────────
SPLASH_HTML = r"""
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
* { margin:0; padding:0; box-sizing:border-box; }
body {
  background: #0B0E17;
  display: flex; flex-direction: column;
  align-items: center; justify-content: center;
  height: 100vh; font-family: 'Segoe UI', sans-serif;
  overflow: hidden;
}
.hex { font-size:52px; color:#4F8EF7; animation: pulse 1.4s ease-in-out infinite; }
.title { color:#E8EDF5; font-size:22px; font-weight:700; margin-top:12px; letter-spacing:.5px; }
.sub { color:#6B7A99; font-size:12px; margin-top:6px; }
.bar-wrap { width:220px; height:3px; background:#1A2030; border-radius:99px; margin-top:28px; overflow:hidden; }
.bar { height:100%; background:linear-gradient(90deg,#4F8EF7,#7C3AED);
       border-radius:99px; animation: load """ + str(0) + r"""ms linear forwards; }
@keyframes pulse { 0%,100%{opacity:1} 50%{opacity:.4} }
@keyframes load  { from{width:0} to{width:100%} }
</style>
</head>
<body>
  <div class="hex">⬡</div>
  <div class="title">{{APP_NAME}}</div>
  <div class="sub">Loading…</div>
  <div class="bar-wrap"><div class="bar" style="animation-duration:{{SPLASH_MS}}ms"></div></div>
</body>
</html>
"""

# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    import webview

    # Start local server
    t = threading.Thread(target=_run_server, daemon=True)
    t.start()
    # Give server a moment to bind
    time.sleep(0.25)

    api = _Api()
    url = f"http://127.0.0.1:{PORT}/index.html"

    if SPLASH_ENABLED:
        # Build splash HTML with correct duration
        splash = SPLASH_HTML.replace("{{APP_NAME}}", APP_NAME)\
                             .replace("{{SPLASH_MS}}", str(SPLASH_DURATION))
        # Write splash to temp
        import tempfile as _tmp
        tmpdir = _tmp.mkdtemp()
        splash_path = os.path.join(tmpdir, "splash.html")
        with open(splash_path, "w", encoding="utf-8") as f:
            f.write(splash)

        splash_win = webview.create_window(
            APP_NAME,
            f"file:///{splash_path}",
            width=480, height=300,
            frameless=True,
            resizable=False,
            on_top=True,
        )

        def _after_splash():
            time.sleep(SPLASH_DURATION / 1000.0)
            main_win = webview.create_window(
                APP_NAME, url,
                width=APP_WIDTH, height=APP_HEIGHT,
                fullscreen=FULLSCREEN,
                resizable=RESIZABLE,
                js_api=api,
                min_size=(400, 300),
            )
            def _inject(w):
                w.evaluate_js(FOOTER_JS)
            main_win.loaded += lambda: webview.windows[1].evaluate_js(FOOTER_JS)
            splash_win.destroy()

        splash_win.loaded += lambda: threading.Thread(target=_after_splash, daemon=True).start()
        webview.start(debug=DEVTOOLS)
    else:
        win = webview.create_window(
            APP_NAME, url,
            width=APP_WIDTH, height=APP_HEIGHT,
            fullscreen=FULLSCREEN,
            resizable=RESIZABLE,
            js_api=api,
            min_size=(400, 300),
        )
        def _on_loaded():
            win.evaluate_js(FOOTER_JS)
        win.loaded += _on_loaded
        webview.start(debug=DEVTOOLS)


if __name__ == "__main__":
    main()
'''


# ══════════════════════════════════════════════════════════════════════════════
#  BuildEngine
# ══════════════════════════════════════════════════════════════════════════════

class BuildEngine:

    # ── Project scanner ───────────────────────────────────────────────────────

    def scan_project(self, folder: str) -> str:
        """Return a tree-style string describing the project structure."""
        lines = []
        has_index = os.path.exists(os.path.join(folder, "index.html"))
        root_name = os.path.basename(folder)
        lines.append(f"📁 {root_name}/")

        stats = {"files": 0, "dirs": 0, "size_kb": 0}
        issues = []

        if not has_index:
            issues.append("⚠  index.html not found! Build will fail.")

        for root, dirs, files in os.walk(folder):
            dirs.sort()
            depth = root.replace(folder, "").count(os.sep)
            indent = "   " * depth
            if depth > 0:
                dname = os.path.basename(root)
                lines.append(f"{indent}📂 {dname}/")
                stats["dirs"] += 1
            for fname in sorted(files)[:20]:   # cap display at 20 per folder
                fpath = os.path.join(root, fname)
                size_kb = os.path.getsize(fpath) / 1024
                stats["files"] += 1
                stats["size_kb"] += size_kb
                icon = self._file_icon(fname)
                lines.append(f"{indent}   {icon} {fname}  ({size_kb:.1f} KB)")
            if len(files) > 20:
                lines.append(f"{indent}   … +{len(files)-20} more files")

        lines.append("")
        lines.append(f"📊  {stats['files']} files · {stats['dirs']} dirs · "
                      f"{stats['size_kb']:.1f} KB total")
        if has_index:
            lines.append("✔  index.html detected — ready to build")
        for issue in issues:
            lines.append(issue)

        return "\n".join(lines)

    @staticmethod
    def _file_icon(name: str) -> str:
        ext = Path(name).suffix.lower()
        icons = {
            ".html": "🌐", ".htm": "🌐",
            ".css":  "🎨",
            ".js":   "⚡", ".mjs": "⚡",
            ".json": "📋",
            ".png":  "🖼", ".jpg": "🖼", ".jpeg": "🖼",
            ".gif":  "🖼", ".svg": "🖼", ".webp": "🖼",
            ".mp4":  "🎬", ".webm": "🎬",
            ".mp3":  "🎵", ".wav": "🎵",
            ".ttf":  "🔤", ".woff": "🔤", ".woff2": "🔤",
            ".ico":  "🔷",
            ".pdf":  "📄",
            ".zip":  "📦",
        }
        return icons.get(ext, "📄")

    # ── Validation ────────────────────────────────────────────────────────────

    def validate(self, input_folder: str) -> list:
        """Return list of error strings (empty = OK)."""
        errors = []
        if not input_folder or not os.path.isdir(input_folder):
            errors.append("Input folder does not exist.")
            return errors
        if not os.path.exists(os.path.join(input_folder, "index.html")):
            errors.append("index.html not found in input folder.")
        return errors

    # ── Icon conversion ───────────────────────────────────────────────────────

    def _prepare_icon(self, icon_path: str, work_dir: str) -> Optional[str]:
        """Convert icon to .ico if needed. Returns path to .ico or None."""
        if not icon_path or not os.path.exists(icon_path):
            return None

        ext = Path(icon_path).suffix.lower()
        ico_dest = os.path.join(work_dir, "app_icon.ico")

        if ext == ".ico":
            shutil.copy2(icon_path, ico_dest)
            return ico_dest

        if not PILLOW_OK:
            return None  # Can't convert without Pillow

        try:
            img = PILImage.open(icon_path).convert("RGBA")
            sizes = [(16,16),(32,32),(48,48),(64,64),(128,128),(256,256)]
            img.save(ico_dest, format="ICO", sizes=sizes)
            return ico_dest
        except Exception:
            return None

    # ── Main build orchestrator ───────────────────────────────────────────────

    def build(self, cfg: dict, progress: Callable[[float, str], None]) -> str:
        """
        Full build pipeline.
        Returns the path to the output .exe on success.
        Raises RuntimeError on failure.
        """
        log_lines = []

        def log(msg: str):
            log_lines.append(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}")

        # ── Validate ──────────────────────────────────────────────────────────
        progress(0.02, "Validating project structure…")
        errors = self.validate(cfg["input_folder"])
        if errors:
            raise RuntimeError("\n".join(errors))
        log("✔ Project validation passed")

        # ── Create temp working directory ──────────────────────────────────────
        progress(0.05, "Preparing build workspace…")
        build_dir = tempfile.mkdtemp(prefix="san_build_")
        log(f"  Work dir: {build_dir}")

        try:
            self._do_build(cfg, build_dir, progress, log)
        except Exception:
            # Write partial log before re-raising
            self._write_log(cfg["output_folder"], log_lines)
            raise
        finally:
            # Clean up temp dir (keep on error for debugging)
            try:
                shutil.rmtree(build_dir, ignore_errors=True)
            except Exception:
                pass

        out_exe = os.path.join(cfg["output_folder"],
                               cfg["app_name"].replace(" ", "_") + ".exe")
        self._write_log(cfg["output_folder"], log_lines)
        return out_exe

    def _do_build(self, cfg: dict, build_dir: str,
                  progress: Callable, log: Callable):

        app_name    = cfg["app_name"].replace(" ", "_")
        input_dir   = cfg["input_folder"]
        output_dir  = cfg["output_folder"]
        os.makedirs(output_dir, exist_ok=True)

        # ── Copy web project ──────────────────────────────────────────────────
        progress(0.10, "Copying HTML project assets…")
        web_project_dest = os.path.join(build_dir, "web_project")
        shutil.copytree(input_dir, web_project_dest, dirs_exist_ok=True)
        asset_count = sum(len(f) for _, _, f in os.walk(web_project_dest))
        log(f"  Copied {asset_count} assets")

        # ── Generate runtime_main.py ──────────────────────────────────────────
        progress(0.20, "Generating runtime engine…")
        runtime_code = RUNTIME_TEMPLATE
        replacements = {
            "{{APP_NAME}}":       cfg["app_name"],
            "{{APP_VERSION}}":    cfg.get("version", "1.0.0"),
            "{{APP_WIDTH}}":      str(cfg.get("width", 1200)),
            "{{APP_HEIGHT}}":     str(cfg.get("height", 800)),
            "{{FULLSCREEN}}":     str(cfg.get("fullscreen", False)),
            "{{RESIZABLE}}":      str(cfg.get("resizable", True)),
            "{{DEVTOOLS}}":       str(cfg.get("devtools", False)),
            "{{SPLASH_ENABLED}}": str(cfg.get("splash_enabled", True)),
            "{{SPLASH_DURATION}}":str(cfg.get("splash_duration", 2500)),
        }
        for k, v in replacements.items():
            runtime_code = runtime_code.replace(k, v)

        runtime_path = os.path.join(build_dir, "runtime_main.py")
        with open(runtime_path, "w", encoding="utf-8") as f:
            f.write(runtime_code)
        log("  Runtime engine generated")

        # ── Prepare icon ──────────────────────────────────────────────────────
        progress(0.28, "Processing icon…")
        icon_path = self._prepare_icon(cfg.get("icon", ""), build_dir)
        if icon_path:
            log(f"  Icon: {os.path.basename(icon_path)}")
        else:
            log("  No icon set (default PyInstaller icon will be used)")

        # ── Write runtime config JSON ─────────────────────────────────────────
        progress(0.32, "Writing runtime config…")
        rt_cfg = {
            "app_name":    cfg["app_name"],
            "version":     cfg.get("version", "1.0.0"),
            "author":      "Developed by Santhosh A",
            "author_url":  AUTHOR_URL,
        }
        with open(os.path.join(build_dir, "app_config.json"), "w") as f:
            json.dump(rt_cfg, f, indent=2)

        # ── Run PyInstaller ───────────────────────────────────────────────────
        progress(0.38, "Running PyInstaller… (this may take 1–3 minutes)")

        sep = ";" if sys.platform == "win32" else ":"

        cmd = [
            sys.executable, "-m", "PyInstaller",
            "--onefile",
            "--noconsole",
            "--clean",
            f"--name={app_name}",
            f"--distpath={output_dir}",
            f"--workpath={os.path.join(build_dir, 'pyinstaller_work')}",
            f"--specpath={build_dir}",
            f"--add-data={web_project_dest}{sep}web_project",
            f"--add-data={os.path.join(build_dir, 'app_config.json')}{sep}.",
        ]

        if icon_path and os.path.exists(icon_path):
            cmd.append(f"--icon={icon_path}")

        # Hidden imports that PyInstaller often misses
        hidden = [
            "webview",
            "webview.platforms.winforms",
            "clr",
        ]
        for h in hidden:
            cmd += ["--hidden-import", h]

        cmd.append(runtime_path)

        log(f"  Command: {' '.join(cmd[:6])} …")

        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            cwd=build_dir,
            text=True,
            encoding="utf-8",
            errors="replace",
        )

        # Stream PyInstaller output
        pi_progress = 0.38
        while True:
            line = proc.stdout.readline()
            if not line and proc.poll() is not None:
                break
            line = line.rstrip()
            if line:
                log(f"  [PyInstaller] {line}")
                # Rough progress estimation
                if "Analyzing" in line:
                    pi_progress = min(0.55, pi_progress + 0.01)
                elif "Collecting" in line:
                    pi_progress = min(0.65, pi_progress + 0.005)
                elif "Building" in line:
                    pi_progress = min(0.80, pi_progress + 0.01)
                elif "PKG" in line or "EXE" in line:
                    pi_progress = min(0.92, pi_progress + 0.02)
                progress(pi_progress, f"PyInstaller: {line[:60]}…")

        rc = proc.wait()
        if rc != 0:
            raise RuntimeError(f"PyInstaller exited with code {rc}. "
                                f"Check build log for details.")

        progress(0.95, "Verifying output…")

        out_exe = os.path.join(output_dir, f"{app_name}.exe")
        if not os.path.exists(out_exe):
            # Try without extension (Linux/Mac)
            alt = os.path.join(output_dir, app_name)
            if os.path.exists(alt):
                out_exe = alt
            else:
                raise RuntimeError("Build seemed to succeed but .exe not found "
                                    f"in {output_dir}")

        size_mb = os.path.getsize(out_exe) / (1024 * 1024)
        log(f"  Output: {out_exe} ({size_mb:.1f} MB)")
        progress(1.0, f"✔ Done — {app_name}.exe ({size_mb:.1f} MB)")

    # ── Log writer ────────────────────────────────────────────────────────────

    @staticmethod
    def _write_log(output_dir: str, lines: list):
        try:
            os.makedirs(output_dir, exist_ok=True)
            log_path = os.path.join(output_dir, "build_log.txt")
            with open(log_path, "w", encoding="utf-8") as f:
                f.write("SanStudio HTML → EXE Converter — Build Log\n")
                f.write("Developed by Santhosh A\n")
                f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write("=" * 60 + "\n\n")
                f.write("\n".join(lines))
                f.write("\n")
        except Exception:
            pass
